name: Amazon Deal Bot

on:
  schedule:
    # Run once per day at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  find-deals:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run Amazon Deal Bot
      env:
        PASTEBIN_API_KEY: ${{ secrets.PASTEBIN_API_KEY }}
      run: |
        python amazon_deals_github.py --api-key "$PASTEBIN_API_KEY"
        
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add amazon_deals_latest.json amazon_deals_latest.csv paste_key.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Update Amazon deals [skip ci]"
        git push
