name: Amazon Deal Bot with GitHub Pages (Enhanced)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  find-deals:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Make script executable
      run: chmod +x amazon_deals_github_pages_enhanced.py
        
    - name: Run Enhanced Amazon Deal Bot
      run: |
        python amazon_deals_github_pages_enhanced.py --simulate
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add docs/
        git commit -m "Update Amazon deals [skip ci]" || echo "No changes to commit"
        git push
