name: Amazon Deal Bot with GitHub Pages

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  find-deals:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run Amazon Deal Bot
      run: |
        python amazon_deals_github_pages.py
        
    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add docs/
        git commit -m "Update Amazon deals [skip ci]" || echo "No changes to commit"
        git push || echo "Nothing to push"
        
    - name: Display GitHub Pages URL
      run: |
        echo "GitHub Pages URL for your Amazon Deals CSV:"
        echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/amazon_deals.csv"
        echo ""
        echo "To use this in Google Sheets, paste this formula in cell A1:"
        echo "=IMPORTDATA(\"https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/amazon_deals.csv\")"
